version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '9999:9999'
    environment:
      PRISMA_CONFIG: |
        port: 9999
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: disco
      POSTGRES_PASSWORD: disco
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~